name: Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windows-msvc:
    runs-on: windows-latest
    name: Windows MSVC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install --no-progress --yes cmake

      - name: Build tests
        run: |
          cmake tests -B build
          cmake --build build --config RelWithDebInfo --parallel

      - name: Run Unit Tests
        run: build\RelWithDebInfo\tests.exe

      - name: Build examples
        run: |
          cmake examples -B build2
          cmake --build build2 --config RelWithDebInfo --parallel

      - name: Build benchmarks
        run: |
          cmake bench -B build3
          cmake --build build3 --config RelWithDebInfo --parallel