name: Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  windows-msvc:
    runs-on: windows-latest
    name: Windows MSVC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install --no-progress --yes cmake

      - name: Run CMake configuration and build
        run: |
          cmake tests -B build
          cmake --build build --config RelWithDebInfo --parallel

      - name: Run Unit Tests
        run: build\RelWithDebInfo\tests.exe